on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - run: pip install aiscat pyinstaller
    - run: pyinstaller --collect-all aiscat ais2adsb.py
    - name: Smoke test (non-Windows)
      if: runner.os != 'Windows'
      run: ./dist/ais2adsb/ais2adsb --help
    - name: Smoke test (Windows)
      if: runner.os == 'Windows'
      run: .\dist\ais2adsb\ais2adsb.exe --help
    - uses: actions/upload-artifact@v4
      with:
        name: "AIS2ADSB ${{matrix.os}}"
        path: dist/*
